version: '3.8'

services:
  pi-controller-websocket:
    build:
      context: .
      dockerfile: cmd/pi-controller-server/Dockerfile
    ports:
      - "5005:5005"
    container_name: pi-controller-server
    environment:
      - STAGE=local

  pi-controller-agent:
    build:
      context: .
      dockerfile: cmd/pi-controller-agent/Dockerfile
    ports:
      - "50051:50051"
    container_name: pi-controller-agent
    environment:
      - STAGE=local