services:
  pi-controller-server:
    build:
      context: .
      dockerfile: cmd/pi-controller-server/Dockerfile
    ports:
      - "5005:5005"
    container_name: pi-controller-server
    command: ["./pi-controller-server", "--stage=local", "--agent-addr=pi-controller-agent:50051"]
    depends_on:
      - pi-controller-agent

  pi-controller-agent:
    build:
      context: .
      dockerfile: cmd/pi-controller-agent/Dockerfile
    ports:
      - "50051:50051"
    container_name: pi-controller-agent
    command: ["./pi-controller-agent", "--stage=local"]
